<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.0" />
    <PackageReference Include="RabbitMQ.Client" Version="7.2.1" />
    <PackageReference Include="MongoDB.Driver" Version="3.8.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/ServiceConnect/ServiceConnect.csproj" />
    <ProjectReference Include="../../src/ServiceConnect.Client.RabbitMQ/ServiceConnect.Client.RabbitMQ.csproj" />
    <ProjectReference Include="../../src/ServiceConnect.Persistence.MongoDb/ServiceConnect.Persistence.MongoDb.csproj" />
  </ItemGroup>
</Project>
