<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <AssemblyName>ServiceConnect.Filters.MessageDeduplication</AssemblyName>
    <PackageId>ServiceConnect.Filters.MessageDeduplication</PackageId>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Common.Logging" Version="3.4.1" />
    <PackageReference Include="mongocsharpdriver" Version="2.4.4" />
    <PackageReference Include="Newtonsoft.Json" Version="10.0.3" />
    <ProjectReference Include="../../../src/ServiceConnect.Interfaces/ServiceConnect.Interfaces.csproj" />
    <PackageReference Include="StackExchange.Redis" Version="1.2.6" />
  </ItemGroup>

</Project>
