//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusSettings
{
    
    
    /// <summary>
    /// The BusSettings Configuration Section.
    /// </summary>
    public partial class BusSettings : global::System.Configuration.ConfigurationSection
    {
        
        #region Singleton Instance
        /// <summary>
        /// The XML name of the BusSettings Configuration Section.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string BusSettingsSectionName = "BusSettings";
        
        /// <summary>
        /// Gets the BusSettings instance.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public static global::BusSettings.BusSettings Instance
        {
            get
            {
                return ((global::BusSettings.BusSettings)(global::System.Configuration.ConfigurationManager.GetSection(global::BusSettings.BusSettings.BusSettingsSectionName)));
            }
        }
        #endregion
        
        #region Xmlns Property
        /// <summary>
        /// The XML name of the <see cref="Xmlns"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string XmlnsPropertyName = "xmlns";
        
        /// <summary>
        /// Gets the XML namespace of this Configuration Section.
        /// </summary>
        /// <remarks>
        /// This property makes sure that if the configuration file contains the XML namespace,
        /// the parser doesn't throw an exception because it encounters the unknown "xmlns" attribute.
        /// </remarks>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::BusSettings.BusSettings.XmlnsPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public string Xmlns
        {
            get
            {
                return ((string)(base[global::BusSettings.BusSettings.XmlnsPropertyName]));
            }
        }
        #endregion
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region EndpointSettings Property
        /// <summary>
        /// The XML name of the <see cref="EndpointSettings"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string EndpointSettingsPropertyName = "EndpointSettings";
        
        /// <summary>
        /// Gets or sets the EndpointSettings.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The EndpointSettings.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::BusSettings.BusSettings.EndpointSettingsPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual global::BusSettings.BusSettingEnpoint EndpointSettings
        {
            get
            {
                return ((global::BusSettings.BusSettingEnpoint)(base[global::BusSettings.BusSettings.EndpointSettingsPropertyName]));
            }
            set
            {
                base[global::BusSettings.BusSettings.EndpointSettingsPropertyName] = value;
            }
        }
        #endregion
    }
}
namespace BusConfiguration
{
    
    
    /// <summary>
    /// The TransportSettings Configuration Element.
    /// </summary>
    public partial class TransportSettings : global::System.Configuration.ConfigurationElement
    {
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region Host Property
        /// <summary>
        /// The XML name of the <see cref="Host"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string HostPropertyName = "Host";
        
        /// <summary>
        /// Gets or sets the Host.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The Host.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::BusConfiguration.TransportSettings.HostPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false, DefaultValue="localhost")]
        public virtual string Host
        {
            get
            {
                return ((string)(base[global::BusConfiguration.TransportSettings.HostPropertyName]));
            }
            set
            {
                base[global::BusConfiguration.TransportSettings.HostPropertyName] = value;
            }
        }
        #endregion
        
        #region Username Property
        /// <summary>
        /// The XML name of the <see cref="Username"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string UsernamePropertyName = "Username";
        
        /// <summary>
        /// Gets or sets the Username.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The Username.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::BusConfiguration.TransportSettings.UsernamePropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual string Username
        {
            get
            {
                return ((string)(base[global::BusConfiguration.TransportSettings.UsernamePropertyName]));
            }
            set
            {
                base[global::BusConfiguration.TransportSettings.UsernamePropertyName] = value;
            }
        }
        #endregion
        
        #region Password Property
        /// <summary>
        /// The XML name of the <see cref="Password"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string PasswordPropertyName = "Password";
        
        /// <summary>
        /// Gets or sets the Password.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The Password.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::BusConfiguration.TransportSettings.PasswordPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual string Password
        {
            get
            {
                return ((string)(base[global::BusConfiguration.TransportSettings.PasswordPropertyName]));
            }
            set
            {
                base[global::BusConfiguration.TransportSettings.PasswordPropertyName] = value;
            }
        }
        #endregion
        
        #region AuditingEnabled Property
        /// <summary>
        /// The XML name of the <see cref="AuditingEnabled"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string AuditingEnabledPropertyName = "AuditingEnabled";
        
        /// <summary>
        /// Gets or sets the AuditingEnabled.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The AuditingEnabled.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::BusConfiguration.TransportSettings.AuditingEnabledPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false, DefaultValue=false)]
        public virtual bool AuditingEnabled
        {
            get
            {
                return ((bool)(base[global::BusConfiguration.TransportSettings.AuditingEnabledPropertyName]));
            }
            set
            {
                base[global::BusConfiguration.TransportSettings.AuditingEnabledPropertyName] = value;
            }
        }
        #endregion
        
        #region ErrorQueueName Property
        /// <summary>
        /// The XML name of the <see cref="ErrorQueueName"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string ErrorQueueNamePropertyName = "ErrorQueueNamee";
        
        /// <summary>
        /// Gets or sets the ErrorQueueName.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The ErrorQueueName.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::BusConfiguration.TransportSettings.ErrorQueueNamePropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false, DefaultValue="errors")]
        public virtual string ErrorQueueName
        {
            get
            {
                return ((string)(base[global::BusConfiguration.TransportSettings.ErrorQueueNamePropertyName]));
            }
            set
            {
                base[global::BusConfiguration.TransportSettings.ErrorQueueNamePropertyName] = value;
            }
        }
        #endregion
        
        #region AuditQueueName Property
        /// <summary>
        /// The XML name of the <see cref="AuditQueueName"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string AuditQueueNamePropertyName = "AuditQueueName";
        
        /// <summary>
        /// Gets or sets the AuditQueueName.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The AuditQueueName.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::BusConfiguration.TransportSettings.AuditQueueNamePropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false, DefaultValue="audit")]
        public virtual string AuditQueueName
        {
            get
            {
                return ((string)(base[global::BusConfiguration.TransportSettings.AuditQueueNamePropertyName]));
            }
            set
            {
                base[global::BusConfiguration.TransportSettings.AuditQueueNamePropertyName] = value;
            }
        }
        #endregion
        
        #region Queue Property
        /// <summary>
        /// The XML name of the <see cref="Queue"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string QueuePropertyName = "Queue";
        
        /// <summary>
        /// Gets or sets the Queue.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The Queue.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::BusConfiguration.TransportSettings.QueuePropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual global::BusSettings.Queue Queue
        {
            get
            {
                return ((global::BusSettings.Queue)(base[global::BusConfiguration.TransportSettings.QueuePropertyName]));
            }
            set
            {
                base[global::BusConfiguration.TransportSettings.QueuePropertyName] = value;
            }
        }
        #endregion
        
        #region Exchange Property
        /// <summary>
        /// The XML name of the <see cref="Exchange"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string ExchangePropertyName = "Exchange";
        
        /// <summary>
        /// Gets or sets the Exchange.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The Exchange.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::BusConfiguration.TransportSettings.ExchangePropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual global::BusSettings.Exchange Exchange
        {
            get
            {
                return ((global::BusSettings.Exchange)(base[global::BusConfiguration.TransportSettings.ExchangePropertyName]));
            }
            set
            {
                base[global::BusConfiguration.TransportSettings.ExchangePropertyName] = value;
            }
        }
        #endregion
        
        #region Retries Property
        /// <summary>
        /// The XML name of the <see cref="Retries"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string RetriesPropertyName = "Retries";
        
        /// <summary>
        /// Gets or sets the Retries.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The Retries.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::BusConfiguration.TransportSettings.RetriesPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual global::BusSettings.Retries Retries
        {
            get
            {
                return ((global::BusSettings.Retries)(base[global::BusConfiguration.TransportSettings.RetriesPropertyName]));
            }
            set
            {
                base[global::BusConfiguration.TransportSettings.RetriesPropertyName] = value;
            }
        }
        #endregion
    }
}
namespace BusSettings
{
    
    
    /// <summary>
    /// A collection of Argument instances.
    /// </summary>
    [global::System.Configuration.ConfigurationCollectionAttribute(typeof(global::BusSettings.Argument), CollectionType=global::System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate, AddItemName=global::BusSettings.Arguments.ArgumentPropertyName)]
    public partial class Arguments : global::System.Configuration.ConfigurationElementCollection
    {
        
        #region Constants
        /// <summary>
        /// The XML name of the individual <see cref="global::BusSettings.Argument"/> instances in this collection.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string ArgumentPropertyName = "Argument";
        #endregion
        
        #region Overrides
        /// <summary>
        /// Gets the type of the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <returns>The <see cref="global::System.Configuration.ConfigurationElementCollectionType"/> of this collection.</returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public override global::System.Configuration.ConfigurationElementCollectionType CollectionType
        {
            get
            {
                return global::System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate;
            }
        }
        
        /// <summary>
        /// Gets the name used to identify this collection of elements
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        protected override string ElementName
        {
            get
            {
                return global::BusSettings.Arguments.ArgumentPropertyName;
            }
        }
        
        /// <summary>
        /// Indicates whether the specified <see cref="global::System.Configuration.ConfigurationElement"/> exists in the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="elementName">The name of the element to verify.</param>
        /// <returns>
        /// <see langword="true"/> if the element exists in the collection; otherwise, <see langword="false"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        protected override bool IsElementName(string elementName)
        {
            return (elementName == global::BusSettings.Arguments.ArgumentPropertyName);
        }
        
        /// <summary>
        /// Gets the element key for the specified configuration element.
        /// </summary>
        /// <param name="element">The <see cref="global::System.Configuration.ConfigurationElement"/> to return the key for.</param>
        /// <returns>
        /// An <see cref="object"/> that acts as the key for the specified <see cref="global::System.Configuration.ConfigurationElement"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        protected override object GetElementKey(global::System.Configuration.ConfigurationElement element)
        {
            return ((global::BusSettings.Argument)(element)).Name;
        }
        
        /// <summary>
        /// Creates a new <see cref="global::BusSettings.Argument"/>.
        /// </summary>
        /// <returns>
        /// A new <see cref="global::BusSettings.Argument"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        protected override global::System.Configuration.ConfigurationElement CreateNewElement()
        {
            return new global::BusSettings.Argument();
        }
        #endregion
        
        #region Indexer
        /// <summary>
        /// Gets the <see cref="global::BusSettings.Argument"/> at the specified index.
        /// </summary>
        /// <param name="index">The index of the <see cref="global::BusSettings.Argument"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public global::BusSettings.Argument this[int index]
        {
            get
            {
                return ((global::BusSettings.Argument)(base.BaseGet(index)));
            }
        }
        
        /// <summary>
        /// Gets the <see cref="global::BusSettings.Argument"/> with the specified key.
        /// </summary>
        /// <param name="Name">The key of the <see cref="global::BusSettings.Argument"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public global::BusSettings.Argument this[object Name]
        {
            get
            {
                return ((global::BusSettings.Argument)(base.BaseGet(Name)));
            }
        }
        #endregion
        
        #region Add
        /// <summary>
        /// Adds the specified <see cref="global::BusSettings.Argument"/> to the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="Argument">The <see cref="global::BusSettings.Argument"/> to add.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public void Add(global::BusSettings.Argument Argument)
        {
            base.BaseAdd(Argument);
        }
        #endregion
        
        #region Remove
        /// <summary>
        /// Removes the specified <see cref="global::BusSettings.Argument"/> from the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="Argument">The <see cref="global::BusSettings.Argument"/> to remove.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public void Remove(global::BusSettings.Argument Argument)
        {
            base.BaseRemove(this.GetElementKey(Argument));
        }
        #endregion
        
        #region GetItem
        /// <summary>
        /// Gets the <see cref="global::BusSettings.Argument"/> at the specified index.
        /// </summary>
        /// <param name="index">The index of the <see cref="global::BusSettings.Argument"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public global::BusSettings.Argument GetItemAt(int index)
        {
            return ((global::BusSettings.Argument)(base.BaseGet(index)));
        }
        
        /// <summary>
        /// Gets the <see cref="global::BusSettings.Argument"/> with the specified key.
        /// </summary>
        /// <param name="Name">The key of the <see cref="global::BusSettings.Argument"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public global::BusSettings.Argument GetItemByKey(string Name)
        {
            return ((global::BusSettings.Argument)(base.BaseGet(((object)(Name)))));
        }
        #endregion
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
    }
}
namespace BusSettings
{
    
    
    /// <summary>
    /// The Argument Configuration Element.
    /// </summary>
    public partial class Argument : global::System.Configuration.ConfigurationElement
    {
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region Name Property
        /// <summary>
        /// The XML name of the <see cref="Name"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string NamePropertyName = "Name";
        
        /// <summary>
        /// Gets or sets the Name.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The Name.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::BusSettings.Argument.NamePropertyName, IsRequired=true, IsKey=true, IsDefaultCollection=false)]
        public virtual string Name
        {
            get
            {
                return ((string)(base[global::BusSettings.Argument.NamePropertyName]));
            }
            set
            {
                base[global::BusSettings.Argument.NamePropertyName] = value;
            }
        }
        #endregion
        
        #region Value Property
        /// <summary>
        /// The XML name of the <see cref="Value"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string ValuePropertyName = "value";
        
        /// <summary>
        /// Gets or sets the Value.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The Value.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::BusSettings.Argument.ValuePropertyName, IsRequired=true, IsKey=false, IsDefaultCollection=false)]
        public virtual string Value
        {
            get
            {
                return ((string)(base[global::BusSettings.Argument.ValuePropertyName]));
            }
            set
            {
                base[global::BusSettings.Argument.ValuePropertyName] = value;
            }
        }
        #endregion
    }
}
namespace BusSettings
{
    
    
    /// <summary>
    /// The Queue Configuration Element.
    /// </summary>
    public partial class Queue : global::System.Configuration.ConfigurationElement
    {
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region Durable Property
        /// <summary>
        /// The XML name of the <see cref="Durable"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string DurablePropertyName = "Durable";
        
        /// <summary>
        /// Gets or sets the Durable.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The Durable.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::BusSettings.Queue.DurablePropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false, DefaultValue=true)]
        public virtual bool Durable
        {
            get
            {
                return ((bool)(base[global::BusSettings.Queue.DurablePropertyName]));
            }
            set
            {
                base[global::BusSettings.Queue.DurablePropertyName] = value;
            }
        }
        #endregion
        
        #region Exclusive Property
        /// <summary>
        /// The XML name of the <see cref="Exclusive"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string ExclusivePropertyName = "Exclusive";
        
        /// <summary>
        /// Gets or sets the Exclusive.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The Exclusive.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::BusSettings.Queue.ExclusivePropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false, DefaultValue=false)]
        public virtual bool Exclusive
        {
            get
            {
                return ((bool)(base[global::BusSettings.Queue.ExclusivePropertyName]));
            }
            set
            {
                base[global::BusSettings.Queue.ExclusivePropertyName] = value;
            }
        }
        #endregion
        
        #region AutoDelete Property
        /// <summary>
        /// The XML name of the <see cref="AutoDelete"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string AutoDeletePropertyName = "AutoDelete";
        
        /// <summary>
        /// Gets or sets the AutoDelete.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The AutoDelete.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::BusSettings.Queue.AutoDeletePropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false, DefaultValue=false)]
        public virtual bool AutoDelete
        {
            get
            {
                return ((bool)(base[global::BusSettings.Queue.AutoDeletePropertyName]));
            }
            set
            {
                base[global::BusSettings.Queue.AutoDeletePropertyName] = value;
            }
        }
        #endregion
        
        #region RoutingKey Property
        /// <summary>
        /// The XML name of the <see cref="RoutingKey"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string RoutingKeyPropertyName = "RoutingKey";
        
        /// <summary>
        /// Gets or sets the RoutingKey.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The RoutingKey.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::BusSettings.Queue.RoutingKeyPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual string RoutingKey
        {
            get
            {
                return ((string)(base[global::BusSettings.Queue.RoutingKeyPropertyName]));
            }
            set
            {
                base[global::BusSettings.Queue.RoutingKeyPropertyName] = value;
            }
        }
        #endregion
        
        #region Name Property
        /// <summary>
        /// The XML name of the <see cref="Name"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string NamePropertyName = "Name";
        
        /// <summary>
        /// Gets or sets the Name.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The Name.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::BusSettings.Queue.NamePropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual string Name
        {
            get
            {
                return ((string)(base[global::BusSettings.Queue.NamePropertyName]));
            }
            set
            {
                base[global::BusSettings.Queue.NamePropertyName] = value;
            }
        }
        #endregion
        
        #region Arguments Property
        /// <summary>
        /// The XML name of the <see cref="Arguments"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string ArgumentsPropertyName = "arguments";
        
        /// <summary>
        /// Gets or sets the Arguments.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The Arguments.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::BusSettings.Queue.ArgumentsPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual global::BusSettings.Arguments Arguments
        {
            get
            {
                return ((global::BusSettings.Arguments)(base[global::BusSettings.Queue.ArgumentsPropertyName]));
            }
            set
            {
                base[global::BusSettings.Queue.ArgumentsPropertyName] = value;
            }
        }
        #endregion
    }
}
namespace BusSettings
{
    
    
    /// <summary>
    /// The Exchange Configuration Element.
    /// </summary>
    public partial class Exchange : global::System.Configuration.ConfigurationElement
    {
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region Name Property
        /// <summary>
        /// The XML name of the <see cref="Name"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string NamePropertyName = "Name";
        
        /// <summary>
        /// Gets or sets the Name.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The Name.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::BusSettings.Exchange.NamePropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual string Name
        {
            get
            {
                return ((string)(base[global::BusSettings.Exchange.NamePropertyName]));
            }
            set
            {
                base[global::BusSettings.Exchange.NamePropertyName] = value;
            }
        }
        #endregion
        
        #region Durable Property
        /// <summary>
        /// The XML name of the <see cref="Durable"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string DurablePropertyName = "Durable";
        
        /// <summary>
        /// Gets or sets the Durable.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The Durable.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::BusSettings.Exchange.DurablePropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false, DefaultValue=false)]
        public virtual bool Durable
        {
            get
            {
                return ((bool)(base[global::BusSettings.Exchange.DurablePropertyName]));
            }
            set
            {
                base[global::BusSettings.Exchange.DurablePropertyName] = value;
            }
        }
        #endregion
        
        #region AutoDelete Property
        /// <summary>
        /// The XML name of the <see cref="AutoDelete"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string AutoDeletePropertyName = "AutoDelete";
        
        /// <summary>
        /// Gets or sets the AutoDelete.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The AutoDelete.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::BusSettings.Exchange.AutoDeletePropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false, DefaultValue=false)]
        public virtual bool AutoDelete
        {
            get
            {
                return ((bool)(base[global::BusSettings.Exchange.AutoDeletePropertyName]));
            }
            set
            {
                base[global::BusSettings.Exchange.AutoDeletePropertyName] = value;
            }
        }
        #endregion
        
        #region Arguments Property
        /// <summary>
        /// The XML name of the <see cref="Arguments"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string ArgumentsPropertyName = "Arguments";
        
        /// <summary>
        /// Gets or sets the Arguments.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The Arguments.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::BusSettings.Exchange.ArgumentsPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual global::BusSettings.Arguments Arguments
        {
            get
            {
                return ((global::BusSettings.Arguments)(base[global::BusSettings.Exchange.ArgumentsPropertyName]));
            }
            set
            {
                base[global::BusSettings.Exchange.ArgumentsPropertyName] = value;
            }
        }
        #endregion
    }
}
namespace BusSettings
{
    
    
    /// <summary>
    /// The Retries Configuration Element.
    /// </summary>
    public partial class Retries : global::System.Configuration.ConfigurationElement
    {
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region MaxRetries Property
        /// <summary>
        /// The XML name of the <see cref="MaxRetries"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string MaxRetriesPropertyName = "MaxRetries";
        
        /// <summary>
        /// Gets or sets the MaxRetries.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The MaxRetries.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::BusSettings.Retries.MaxRetriesPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false, DefaultValue=3)]
        public virtual int MaxRetries
        {
            get
            {
                return ((int)(base[global::BusSettings.Retries.MaxRetriesPropertyName]));
            }
            set
            {
                base[global::BusSettings.Retries.MaxRetriesPropertyName] = value;
            }
        }
        #endregion
        
        #region RetryDelay Property
        /// <summary>
        /// The XML name of the <see cref="RetryDelay"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string RetryDelayPropertyName = "RetryDelay";
        
        /// <summary>
        /// Gets or sets the RetryDelay.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The RetryDelay.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::BusSettings.Retries.RetryDelayPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false, DefaultValue=3000)]
        public virtual int RetryDelay
        {
            get
            {
                return ((int)(base[global::BusSettings.Retries.RetryDelayPropertyName]));
            }
            set
            {
                base[global::BusSettings.Retries.RetryDelayPropertyName] = value;
            }
        }
        #endregion
        
        #region Arguments Property
        /// <summary>
        /// The XML name of the <see cref="Arguments"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string ArgumentsPropertyName = "arguments";
        
        /// <summary>
        /// Gets or sets the Arguments.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The Arguments.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::BusSettings.Retries.ArgumentsPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual global::BusSettings.Arguments Arguments
        {
            get
            {
                return ((global::BusSettings.Arguments)(base[global::BusSettings.Retries.ArgumentsPropertyName]));
            }
            set
            {
                base[global::BusSettings.Retries.ArgumentsPropertyName] = value;
            }
        }
        #endregion
    }
}
namespace BusConfiguration
{
    
    
    /// <summary>
    /// The PersistanceSettings Configuration Element.
    /// </summary>
    public partial class PersistanceSettings : global::System.Configuration.ConfigurationElement
    {
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region Database Property
        /// <summary>
        /// The XML name of the <see cref="Database"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string DatabasePropertyName = "Database";
        
        /// <summary>
        /// Gets or sets the Database.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The Database.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::BusConfiguration.PersistanceSettings.DatabasePropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false, DefaultValue="RMessageBusPersistantStore")]
        public virtual string Database
        {
            get
            {
                return ((string)(base[global::BusConfiguration.PersistanceSettings.DatabasePropertyName]));
            }
            set
            {
                base[global::BusConfiguration.PersistanceSettings.DatabasePropertyName] = value;
            }
        }
        #endregion
        
        #region ConnectionString Property
        /// <summary>
        /// The XML name of the <see cref="ConnectionString"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string ConnectionStringPropertyName = "ConnectionString";
        
        /// <summary>
        /// Gets or sets the ConnectionString.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The ConnectionString.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::BusConfiguration.PersistanceSettings.ConnectionStringPropertyName, IsRequired=true, IsKey=true, IsDefaultCollection=false, DefaultValue="mongodb://localhost/")]
        public virtual string ConnectionString
        {
            get
            {
                return ((string)(base[global::BusConfiguration.PersistanceSettings.ConnectionStringPropertyName]));
            }
            set
            {
                base[global::BusConfiguration.PersistanceSettings.ConnectionStringPropertyName] = value;
            }
        }
        #endregion
    }
}
namespace BusSettings
{
    
    
    /// <summary>
    /// A collection of EndpointSettings instances.
    /// </summary>
    [global::System.Configuration.ConfigurationCollectionAttribute(typeof(global::BusSettings.EndpointSettings), CollectionType=global::System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate, AddItemName=global::BusSettings.BusSettingEnpoint.EndpointSettingsPropertyName)]
    public partial class BusSettingEnpoint : global::System.Configuration.ConfigurationElementCollection
    {
        
        #region Constants
        /// <summary>
        /// The XML name of the individual <see cref="global::BusSettings.EndpointSettings"/> instances in this collection.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string EndpointSettingsPropertyName = "Enpoint";
        #endregion
        
        #region Overrides
        /// <summary>
        /// Gets the type of the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <returns>The <see cref="global::System.Configuration.ConfigurationElementCollectionType"/> of this collection.</returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public override global::System.Configuration.ConfigurationElementCollectionType CollectionType
        {
            get
            {
                return global::System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate;
            }
        }
        
        /// <summary>
        /// Gets the name used to identify this collection of elements
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        protected override string ElementName
        {
            get
            {
                return global::BusSettings.BusSettingEnpoint.EndpointSettingsPropertyName;
            }
        }
        
        /// <summary>
        /// Indicates whether the specified <see cref="global::System.Configuration.ConfigurationElement"/> exists in the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="elementName">The name of the element to verify.</param>
        /// <returns>
        /// <see langword="true"/> if the element exists in the collection; otherwise, <see langword="false"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        protected override bool IsElementName(string elementName)
        {
            return (elementName == global::BusSettings.BusSettingEnpoint.EndpointSettingsPropertyName);
        }
        
        /// <summary>
        /// Gets the element key for the specified configuration element.
        /// </summary>
        /// <param name="element">The <see cref="global::System.Configuration.ConfigurationElement"/> to return the key for.</param>
        /// <returns>
        /// An <see cref="object"/> that acts as the key for the specified <see cref="global::System.Configuration.ConfigurationElement"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        protected override object GetElementKey(global::System.Configuration.ConfigurationElement element)
        {
            return ((global::BusSettings.EndpointSettings)(element)).Name;
        }
        
        /// <summary>
        /// Creates a new <see cref="global::BusSettings.EndpointSettings"/>.
        /// </summary>
        /// <returns>
        /// A new <see cref="global::BusSettings.EndpointSettings"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        protected override global::System.Configuration.ConfigurationElement CreateNewElement()
        {
            return new global::BusSettings.EndpointSettings();
        }
        #endregion
        
        #region Indexer
        /// <summary>
        /// Gets the <see cref="global::BusSettings.EndpointSettings"/> at the specified index.
        /// </summary>
        /// <param name="index">The index of the <see cref="global::BusSettings.EndpointSettings"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public global::BusSettings.EndpointSettings this[int index]
        {
            get
            {
                return ((global::BusSettings.EndpointSettings)(base.BaseGet(index)));
            }
        }
        
        /// <summary>
        /// Gets the <see cref="global::BusSettings.EndpointSettings"/> with the specified key.
        /// </summary>
        /// <param name="name">The key of the <see cref="global::BusSettings.EndpointSettings"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public global::BusSettings.EndpointSettings this[object name]
        {
            get
            {
                return ((global::BusSettings.EndpointSettings)(base.BaseGet(name)));
            }
        }
        #endregion
        
        #region Add
        /// <summary>
        /// Adds the specified <see cref="global::BusSettings.EndpointSettings"/> to the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="Enpoint">The <see cref="global::BusSettings.EndpointSettings"/> to add.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public void Add(global::BusSettings.EndpointSettings Enpoint)
        {
            base.BaseAdd(Enpoint);
        }
        #endregion
        
        #region Remove
        /// <summary>
        /// Removes the specified <see cref="global::BusSettings.EndpointSettings"/> from the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="Enpoint">The <see cref="global::BusSettings.EndpointSettings"/> to remove.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public void Remove(global::BusSettings.EndpointSettings Enpoint)
        {
            base.BaseRemove(this.GetElementKey(Enpoint));
        }
        #endregion
        
        #region GetItem
        /// <summary>
        /// Gets the <see cref="global::BusSettings.EndpointSettings"/> at the specified index.
        /// </summary>
        /// <param name="index">The index of the <see cref="global::BusSettings.EndpointSettings"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public global::BusSettings.EndpointSettings GetItemAt(int index)
        {
            return ((global::BusSettings.EndpointSettings)(base.BaseGet(index)));
        }
        
        /// <summary>
        /// Gets the <see cref="global::BusSettings.EndpointSettings"/> with the specified key.
        /// </summary>
        /// <param name="name">The key of the <see cref="global::BusSettings.EndpointSettings"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public global::BusSettings.EndpointSettings GetItemByKey(string name)
        {
            return ((global::BusSettings.EndpointSettings)(base.BaseGet(((object)(name)))));
        }
        #endregion
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
    }
}
namespace BusSettings
{
    
    
    /// <summary>
    /// The EndpointSettings Configuration Element.
    /// </summary>
    public partial class EndpointSettings : global::System.Configuration.ConfigurationElement
    {
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region Name Property
        /// <summary>
        /// The XML name of the <see cref="Name"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string NamePropertyName = "name";
        
        /// <summary>
        /// Gets or sets the Name.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The Name.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::BusSettings.EndpointSettings.NamePropertyName, IsRequired=true, IsKey=true, IsDefaultCollection=false)]
        public virtual string Name
        {
            get
            {
                return ((string)(base[global::BusSettings.EndpointSettings.NamePropertyName]));
            }
            set
            {
                base[global::BusSettings.EndpointSettings.NamePropertyName] = value;
            }
        }
        #endregion
        
        #region TransportSettings Property
        /// <summary>
        /// The XML name of the <see cref="TransportSettings"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string TransportSettingsPropertyName = "TransportSettings";
        
        /// <summary>
        /// Gets or sets the TransportSettings.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The TransportSettings.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::BusSettings.EndpointSettings.TransportSettingsPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual global::BusConfiguration.TransportSettings TransportSettings
        {
            get
            {
                return ((global::BusConfiguration.TransportSettings)(base[global::BusSettings.EndpointSettings.TransportSettingsPropertyName]));
            }
            set
            {
                base[global::BusSettings.EndpointSettings.TransportSettingsPropertyName] = value;
            }
        }
        #endregion
        
        #region PersistanceSettings Property
        /// <summary>
        /// The XML name of the <see cref="PersistanceSettings"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string PersistanceSettingsPropertyName = "PersistanceSettings";
        
        /// <summary>
        /// Gets or sets the PersistanceSettings.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The PersistanceSettings.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::BusSettings.EndpointSettings.PersistanceSettingsPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual global::BusConfiguration.PersistanceSettings PersistanceSettings
        {
            get
            {
                return ((global::BusConfiguration.PersistanceSettings)(base[global::BusSettings.EndpointSettings.PersistanceSettingsPropertyName]));
            }
            set
            {
                base[global::BusSettings.EndpointSettings.PersistanceSettingsPropertyName] = value;
            }
        }
        #endregion
    }
}
