<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<TargetFrameworks>net10.0</TargetFrameworks>
    <AssemblyName>ServiceConnect.Interfaces</AssemblyName>
    <PackageId>ServiceConnect.Interfaces</PackageId>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
    <Version>6.0.0</Version>
    <Description>ServiceConnect Interfaces</Description>
  </PropertyGroup>

</Project>
